name: Build

on: [push, pull_request_target]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ['linux']
        arch: ['x86', 'x64']

    steps:
      - uses: actions/checkout@v2
      - name: Install 32 bit support
        run: sudo apt-get install gcc-multilib g++-multilib

      - name: Build
        run: .github/scripts/compile.sh ${{ matrix.platform }} ${{ matrix.arch }} ${{ matrix.buildmode }}
      - name: Run
        run: .github/scripts/run_tests.sh

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: ['linux']
        arch: ['x64']
        buildmode: ['release']

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: .github/scripts/compile.sh ${{ matrix.platform }} ${{ matrix.arch }} ${{ matrix.buildmode }}
      - name: Run
        run: .github/scripts/run_tests.sh


  build-windows:
    runs-on: 'windows-latest'

    strategy:
      matrix:
        platform: ['windows']
        arch: ['x86', 'x64']
        buildmode: ['debug', 'release']
        toolset: ['14.3','14.2','14.1']

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ matrix.toolset }}
      - name: Build
        run: .github/scripts/compile.bat ${{ matrix.platform }} ${{ matrix.arch }} ${{ matrix.buildmode }}
      - name: Run
        run: .github/scripts/run_tests.bat

  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ['android']
        arch: ['armv7', 'arm64']
        buildmode: ['release']

    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          java-version: 1.11

      # Sets ANDROID_HOME
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: sdkmanager --verbose "${{ matrix.ndkversion }}"

      - name: Build
        run: .github/scripts/compile.sh ${{ matrix.platform }} ${{ matrix.arch }} ${{ matrix.buildmode }}
        env:
          ANDROID_NDK_HOME: $ANDROID_HOME/ndk/ndk;22.0.7026061
          ANDROID_NDK_API_VERSION: 22

      # - name: Run
      #   run: .github/scripts/run_tests.sh


